###
GET localhost:8080/userdata/library/1
###
###
POST localhost:8080/userdata/save?userId=1&patternId=5
###
###
DELETE localhost:8080/userdata/delete?userId=1&patternId=3
###
###
POST localhost:8080/userdata/complete?userId=1&patternId=1
###
###
GET localhost:8080/userdata/progress/1/1
###
###
POST localhost:8080/userdata/progress/1/1?stepIndex=3
###