###
GET localhost:8080/notes/1
###
###
POST localhost:8080/notes/add?userDataId=2&content=new note for pattern2
###
###
PUT localhost:8080/notes/update?noteId=1&content=updated note1
###
###
DELETE localhost:8080/notes/delete/4
###