###
GET localhost:8080/pattern/all
###
###
GET localhost:8080/pattern/filtered
###
###
GET localhost:8080/pattern/filtered?categoryId=1&yarnId=6&difficulty=intermediate
###
###
GET localhost:8080/pattern/filtered?yarnId=5
###
###
GET localhost:8080/pattern/filtered?categoryId=2&difficulty=beginner
###